% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Estimating time of extinction using an optimal linear estimator},
  pdfauthor={C. George Glen},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Estimating time of extinction using an optimal linear estimator}
\author{C. George Glen}
\date{2022-04-09}

\begin{document}
\maketitle

This analysis is recreating that made by
\href{https://www.nature.com/articles/426245a}{Roberts and Solow
(2003)}.

\hypertarget{theory}{%
\subsection{Theory}\label{theory}}

Going off \href{https://www.nature.com/articles/426245a}{Roberts and
Solow (2003)}, if we let \(T_1 > T_2 > ... > T_n\) be the \(k\) most
recent sightings of a species, ordered from the most to least recent,
then we can use these observations to estimate, \(\hat\theta\), or the
estimate time of extinction.

An important result is that of
\href{https://academic.oup.com/biomet/article-abstract/67/1/257/276536}{Cooke
(1980)}, who showed the joint distribution of the \(k\) most recent
sightings has an approximate ``Weibull form'', regardless of the
distribution of the (unknown) complete sightings record. The parameter,
\(\theta\), is then optimal linear estimator for the extinction time.

The parameter, \(\theta\), is computed as the weighted sum of the
sightings

\[ 
\hat\theta = \sum^k_{i=1} a_i T_i
\]

Where \(a_i\) is a vector of weights, computed as

\[
a_i = (e^T \Lambda^{-1} e)^{-1} \Lambda^{-1} e
\]

Where \(e\) is a vector of \(k\) 1's, \(\Lambda\) is the symmetric
\(k \cdot k\) matrix with typical element equal to

\[
\hat\lambda_{ij} = \frac{\Gamma(2 \hat\upsilon + i) \Gamma(\hat\upsilon + j) }{\Gamma(\hat\upsilon + i)\Gamma(j)}, j \leq i 
\]

And \(\Gamma()\) is the standard Gamma function.

Finally, \(\hat\upsilon\) is an estimate of the shape parameter for the
joint Weibull distribution of the k most recent sighting times, and is
computed as

\[
\hat\upsilon = \frac{1}{k-1}\sum_{i-1}^{k-2} log \frac{T_1 - T_k}{T_1 - T_{i+1}}
\]

We an also compute 95\% confidence intervals as

\[
\hat\theta_{95\% \;CI}= (T_1 + \frac{T_1 - T_k}{S_L - 1},T_1 \frac{T_1 - T_k}{S_U - 1})
\\
S_L = \Big(\frac{-log ( 1-\frac{\alpha}{2}) }{k}\Big)^{-\hat\upsilon} 
\\
S_U = \Big(\frac{-log (\frac{\alpha}{2}) }{k}\Big)^{-\hat\upsilon}
\]

\hypertarget{example-dodo}{%
\subsection{Example: Dodo}\label{example-dodo}}

Let's now apply this to the Dodo.

The last observations for the dodo, given in
\href{https://www.nature.com/articles/426245a}{Roberts and Solow
(2003)}, are

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dodosightingtimes }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1662}\NormalTok{, }\DecValTok{1638}\NormalTok{, }\DecValTok{1631}\NormalTok{, }\DecValTok{1628}\NormalTok{, }\DecValTok{1628}\NormalTok{, }\DecValTok{1611}\NormalTok{, }\DecValTok{1607}\NormalTok{, }\DecValTok{1602}\NormalTok{, }\DecValTok{1601}\NormalTok{, }\DecValTok{1598}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The optimal linear estimator, \(\hat\theta\), and the associated 95\% CI
are computed as

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{OLE }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(data, alpha)\{}
    
    \DocumentationTok{\#\# sort the data and define a parameter for length (here k)}
\NormalTok{    obs }\OtherTok{\textless{}{-}} \FunctionTok{rev}\NormalTok{(}\FunctionTok{sort}\NormalTok{(data))}
\NormalTok{    k   }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(obs)}
    
    \DocumentationTok{\#\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
    \DocumentationTok{\#\# compute v, e, lambda, and a}
    \DocumentationTok{\#\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
    
    \DocumentationTok{\#\# estimate the shape parameter of the joint Weibull distribution }
    \DocumentationTok{\#\# 4th equation in Roberts and Solow 2003}
\NormalTok{    v }\OtherTok{\textless{}{-}}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{/}\NormalTok{(k}\DecValTok{{-}1}\NormalTok{)) }\SpecialCharTok{*} \FunctionTok{sum}\NormalTok{(}\FunctionTok{log}\NormalTok{((obs[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{{-}}\NormalTok{ obs[k])}\SpecialCharTok{/}\NormalTok{(obs[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{{-}}\NormalTok{ obs[}\DecValTok{2}\SpecialCharTok{:}\NormalTok{(k}\DecValTok{{-}1}\NormalTok{)])))}
    
    \DocumentationTok{\#\# define a vector of k 1’s}
\NormalTok{    e }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{,k), }\AttributeTok{ncol=}\DecValTok{1}\NormalTok{)}
    
    \DocumentationTok{\#\# Λ is the symmetric k x k matrix with typical element}
\NormalTok{    lambda }\OtherTok{\textless{}{-}} \FunctionTok{compute.lambda}\NormalTok{(obs, v)}
    \DocumentationTok{\#\# make the Λ matrix symmetric}
\NormalTok{    lambda }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{lower.tri}\NormalTok{(lambda), lambda, }\FunctionTok{t}\NormalTok{(lambda)) }
    
    \DocumentationTok{\#\# vector of weights is given by: a = (e\^{}t * Λ\^{}{-}1 * e)\^{}{-}1 * Λ\^{}{-}1*e}
\NormalTok{    a      }\OtherTok{\textless{}{-}} \FunctionTok{as.vector}\NormalTok{(}\FunctionTok{solve}\NormalTok{(}\FunctionTok{t}\NormalTok{(e) }\SpecialCharTok{\%*\%} \FunctionTok{solve}\NormalTok{(lambda) }\SpecialCharTok{\%*\%}\NormalTok{ e)) }\SpecialCharTok{*} \FunctionTok{solve}\NormalTok{(lambda) }\SpecialCharTok{\%*\%}\NormalTok{ e}
    
    \DocumentationTok{\#\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
    \DocumentationTok{\#\# calculate confidence intervals}
    \DocumentationTok{\#\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{    SL     }\OtherTok{\textless{}{-}}\NormalTok{ (}\SpecialCharTok{{-}}\FunctionTok{log}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{alpha}\SpecialCharTok{/}\DecValTok{2}\NormalTok{)}\SpecialCharTok{/}\FunctionTok{length}\NormalTok{(obs))}\SpecialCharTok{\^{}{-}}\NormalTok{v}
\NormalTok{    SU     }\OtherTok{\textless{}{-}}\NormalTok{ (}\SpecialCharTok{{-}}\FunctionTok{log}\NormalTok{(alpha}\SpecialCharTok{/}\DecValTok{2}\NormalTok{)}\SpecialCharTok{/}\FunctionTok{length}\NormalTok{(obs))}\SpecialCharTok{\^{}{-}}\NormalTok{v}
\NormalTok{    lowerCI }\OtherTok{\textless{}{-}} \FunctionTok{max}\NormalTok{(obs) }\SpecialCharTok{+}\NormalTok{ ((}\FunctionTok{max}\NormalTok{(obs)}\SpecialCharTok{{-}}\FunctionTok{min}\NormalTok{(obs))}\SpecialCharTok{/}\NormalTok{(SL}\DecValTok{{-}1}\NormalTok{)) }\DocumentationTok{\#\# lower confidence interval}
\NormalTok{    upperCI }\OtherTok{\textless{}{-}} \FunctionTok{max}\NormalTok{(obs) }\SpecialCharTok{+}\NormalTok{ ((}\FunctionTok{max}\NormalTok{(obs)}\SpecialCharTok{{-}}\FunctionTok{min}\NormalTok{(obs))}\SpecialCharTok{/}\NormalTok{(SU}\DecValTok{{-}1}\NormalTok{)) }\DocumentationTok{\#\# upper confidence interval}
    
    \DocumentationTok{\#\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
    \DocumentationTok{\#\# compute time of extinction}
    \DocumentationTok{\#\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{    extincttime }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{t}\NormalTok{(a)}\SpecialCharTok{\%*\%}\NormalTok{obs)}
    
    \DocumentationTok{\#\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
    \DocumentationTok{\#\# return a dataframe}
    \DocumentationTok{\#\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{    res }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Estimate=}\NormalTok{extincttime, }\AttributeTok{lowerCI=}\NormalTok{lowerCI, }\AttributeTok{upperCI=}\NormalTok{upperCI)}
    
    \DocumentationTok{\#\#return the results}
    \FunctionTok{return}\NormalTok{(res)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

And \(\Lambda\) is computed using the function

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{compute.lambda }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(dates, v)\{}
\NormalTok{  n      }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(dates)}
\NormalTok{  lambda }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\AttributeTok{data=}\ConstantTok{NA}\NormalTok{, }\AttributeTok{nrow=}\NormalTok{n, }\AttributeTok{ncol=}\NormalTok{n)}
  \ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{n)\{}
    \ControlFlowTok{for}\NormalTok{(j }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{n)\{}
\NormalTok{      lambda[i,j] }\OtherTok{\textless{}{-}}\NormalTok{ (}\FunctionTok{gamma}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{v }\SpecialCharTok{+}\NormalTok{ i) }\SpecialCharTok{*} \FunctionTok{gamma}\NormalTok{(v }\SpecialCharTok{+}\NormalTok{ j))}\SpecialCharTok{/}\NormalTok{(}\FunctionTok{gamma}\NormalTok{(v }\SpecialCharTok{+}\NormalTok{ i) }\SpecialCharTok{*} \FunctionTok{gamma}\NormalTok{(j))}
\NormalTok{    \}}
\NormalTok{  \}}
  \FunctionTok{return}\NormalTok{(lambda)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{OLE}\NormalTok{(}\AttributeTok{data=}\NormalTok{dodosightingtimes, }\AttributeTok{alpha=}\FloatTok{0.05}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Estimate  lowerCI  upperCI
## 1 1690.418 1669.133 1798.879
\end{verbatim}

This is equal to the estimates of
\href{https://www.nature.com/articles/426245a}{Roberts and Solow
(2003)}: \[
Estimate = 1690\\
lowerCI = 1669\\  
upperCI = 1799\\
\]

\end{document}
